### ISSUE TITLE
Cuda problem

### ISSUE THREAD

**Issue by H-EKE** [gcorso/DiffDock#104]
Hi ,

Each time that I try to run diff dock I get the following message:

```

/.conda/envs/diffdock/lib/python3.8/site-packages/torch_geometric/typing.py:31: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: /.conda/envs/diffdock/lib/python3.8/site-packa
ges/torch_scatter/_scatter_cuda.so: undefined symbol: _ZN2at4_ops6narrow4callERKNS_6TensorElll
  warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
/.conda/envs/diffdock/lib/python3.8/site-packages/torch_geometric/typing.py:42: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: /.conda/envs/diffdock/lib/python3.8/site-packag
es/torch_sparse/_diag_cuda.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb
  warnings.warn(f"An issue occurred while importing 'torch-sparse'. "
Traceback (most recent call last):
  File "/.conda/envs/diffdock/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/.conda/envs/diffdock/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/DiffDock/DiffDock/inference.py", line 10, in <module>
    from torch_geometric.loader import DataLoader
  File "/.conda/envs/diffdock/lib/python3.8/site-packages/torch_geometric/__init__.py", line 1, in <module>
    import torch_geometric.utils
  File "/.conda/envs/diffdock/lib/python3.8/site-packages/torch_geometric/utils/__init__.py", line 8, in <module>
    from .dropout import dropout_adj, dropout_node, dropout_edge, dropout_path
  File "/.conda/envs/diffdock/lib/python3.8/site-packages/torch_geometric/utils/dropout.py", line 6, in <module>
    import torch_cluster  # noqa
  File ".conda/envs/diffdock/lib/python3.8/site-packages/torch_cluster/__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File ".conda/envs/diffdock/lib/python3.8/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/.conda/envs/diffdock/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /.conda/envs/diffdock/lib/python3.8/site-packages/torch_cluster/_grid_cuda.so: undefined symbol: _ZN2at4_ops6narrow4callERKNS_6TensorElll
````

Would you any suggestion to solve this issue?

Thanks in advance

**Comment by gcorso** [comment]
Hi @H-EKE 

This seems to be an issue with `torch_cluster`. Unfortunately I also frequently have issue with `torch_cluster` when setting up new environments. 
My suggestions are (in this order): create a new environment, install PyTorch being careful to select on the PyTorch website the command for the CUDA version that you have installed on the GPU, install PyTorch geometric with all its packages being careful that you are taking the one supporting the same CUDA version.

I hope this helps,
Gabriele

**Comment by H-EKE** [comment]
Dear @gcorso ,

Thanks for your fast reply!

**Comment by dan9thsense** [comment]
see issue #113
