### ISSUE TITLE
ModuleNotFoundError: No module named 'scripts.utils'

### ISSUE THREAD

**Issue by Shreyas-Bhat** [gcorso/DiffDock#109]
Hi all,
I am facing this error when trying to run this line of the installation process - ```pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307' ```
Could you please help me out here if you have successfully completed this step?

 ```× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_c5kp1xc/openfold_6481422afc0840fe989b4c59dd688ac7/setup.py", line 21, in <module>
          from scripts.utils import get_nvidia_cc
      ModuleNotFoundError: No module named 'scripts.utils'
      [end of output]
      ```

**Comment by dan9thsense** [comment]
Same problem; have not found a solution yet.  There is a pip package `scripts` but it does not have .utils

**Comment by evancollins1** [comment]
@Shreyas-Bhat @dan9thsense any updates on this issue?

**Comment by gcorso** [comment]
Hi all, apologies for the delay, those lines were copied from the ESM installation commands, you can find [here](https://github.com/facebookresearch/esm#getting-started-with-this-repo-) some suggestions on how to try to solve the issue. I hope this helps!
