### ISSUE TITLE
Exception: Bad Conformer ID

### ISSUE THREAD

**Issue by KruskalLin** [gcorso/DiffDock#13]
When I run the training code on the small score model, it throws an exception during the preprocessing

```python
loading complexes:   3%|▎         | 493/16379 [43:30<23:21:46,  5.29s/it]
Traceback (most recent call last):
  File "anaconda3/envs/diffdock/lib/python3.10/site-packages/scipy/optimize/_differentialevolution.py", line 1116, in _calculate_population_energies
    calc_energies = list(
  File "anaconda3/envs/diffdock/lib/python3.10/site-packages/scipy/_lib/_util.py", line 407, in __call__
    return self.f(x, *self.args)
  File "diffdock/datasets/conformer_matching.py", line 60, in score_conformation
    SetDihedral(self.mol.GetConformer(self.probe_id), r, values[i])
ValueError: Bad Conformer Id
```
This is the exception thrown in conformer matching file. I am not sure if it is only me or it's the codes. Could you please take a look? Or do you see this exception before?

**Comment by KruskalLin** [comment]
I see the `pdbbind.py` file has been changed, and [line 321](https://github.com/gcorso/DiffDock/blob/0b3a1f8d1a39b80dd17b528c48e77bb1cfb9b54d/datasets/pdbbind.py#L321) in `get_complexes` method did not appear in the original file in the anonymized repository. Should this line be deleted? You can also see the comment below.
```python
        for i, lig in enumerate(ligs):
            if self.max_lig_size is not None and lig.GetNumHeavyAtoms() > self.max_lig_size:
                print(f'Ligand with {lig.GetNumHeavyAtoms()} heavy atoms is larger than max_lig_size {self.max_lig_size}. Not including {name} in preprocessed data.')
                continue
            complex_graph = HeteroData()
            complex_graph['name'] = name
            try:
                get_lig_graph_with_matching(lig, complex_graph, self.popsize, self.maxiter, self.matching, self.keep_original,
                                            self.num_conformers, remove_hs=self.remove_hs)
                rec, rec_coords, c_alpha_coords, n_coords, c_coords, lm_embeddings = extract_receptor_structure(copy.deepcopy(rec_model), lig, lm_embedding_chains=lm_embedding_chains)
                if lm_embeddings is not None and len(c_alpha_coords) != len(lm_embeddings):
                    print(f'LM embeddings for complex {name} did not have the right length for the protein. Skipping {name}.')
                    continue

                get_rec_graph(rec, rec_coords, c_alpha_coords, n_coords, c_coords, complex_graph, rec_radius=self.receptor_radius,
                              c_alpha_max_neighbors=self.c_alpha_max_neighbors, all_atoms=self.all_atoms,
                              atom_radius=self.atom_radius, atom_max_neighbors=self.atom_max_neighbors, remove_hs=self.remove_hs, lm_embeddings=lm_embeddings)

            except Exception as e:
                print(f'Skipping {name} because of the error:')
                print(e)
                raise e # Is this line corrected?
                continue
```

**Comment by gcorso** [comment]
Thank you for noticing, indeed the raise was added only for debugging purposes. My understanding is that the reason why the error is raised is that RDKit fails to generate a conformer for the given ligand (even when set to use random coordinates, which is very rare). Therefore, since the conformer matching procedure relies on the starting RDKit conformer the routine fails. Without the raise, the complexes where RDKit cannot embed the conformer are just discarded.
