### ISSUE TITLE
Issue with running inference.py

### ISSUE THREAD

**Issue by Tenchberry** [gcorso/DiffDock#130]
Hi there. I recently installed DiffDock, with all steps of the installation proceeding fine. When I attempted to test the installation by running the inference example in the README, the following traceback was returned:-

/home/khaledabdel/software/miniconda3/envs/diffdock/lib/python3.8/site-packages/torch_geometric/typing.py:31: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: /home/khaledabdel/software/miniconda3/envs/diffdock/lib/python3.8/site-packages/torch_scatter/_scatter_cuda.so: undefined symbol: _ZN2at4_ops6narrow4callERKNS_6TensorElll
  warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
/home/khaledabdel/software/miniconda3/envs/diffdock/lib/python3.8/site-packages/torch_geometric/typing.py:42: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: /home/khaledabdel/software/miniconda3/envs/diffdock/lib/python3.8/site-packages/torch_sparse/_diag_cuda.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb
  warnings.warn(f"An issue occurred while importing 'torch-sparse'. "
Traceback (most recent call last):
  File "inference.py", line 10, in <module>
    from torch_geometric.loader import DataLoader
  File "/home/khaledabdel/software/miniconda3/envs/diffdock/lib/python3.8/site-packages/torch_geometric/__init__.py", line 1, in <module>
    import torch_geometric.utils
  File "/home/khaledabdel/software/miniconda3/envs/diffdock/lib/python3.8/site-packages/torch_geometric/utils/__init__.py", line 8, in <module>
    from .dropout import dropout_adj, dropout_node, dropout_edge, dropout_path
  File "/home/khaledabdel/software/miniconda3/envs/diffdock/lib/python3.8/site-packages/torch_geometric/utils/dropout.py", line 6, in <module>
    import torch_cluster  # noqa
  File "/home/khaledabdel/software/miniconda3/envs/diffdock/lib/python3.8/site-packages/torch_cluster/__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/khaledabdel/software/miniconda3/envs/diffdock/lib/python3.8/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/home/khaledabdel/software/miniconda3/envs/diffdock/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/khaledabdel/software/miniconda3/envs/diffdock/lib/python3.8/site-packages/torch_cluster/_grid_cuda.so: undefined symbol: _ZN2at4_ops6narrow4callERKNS_6TensorElll

From looking at this, it seems like something went wrong with the installation, as it appears some packages cannot be imported properly. A bit of clarification would be highly appreciative here.

System is a CentOS 7 machine, with CUDA 12.0 installed.

Thanks for your time

**Comment by Xu-kexin** [comment]
It may because your CUDA and torch version is not match, my suggestion is to check from the official website of pytorch and reinstall them.

**Comment by Ariyaris** [comment]
In my case running:
python -m inference.py --protein_ligand_csv data/protein_ligand_example_csv.csv --out_dir results/user_predictions_small --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise
caused the following error:
Segmentation fault
(or Aborted) 

Could this also be the problem with the CUDA and pytorch? (I followed the exact installation as described in the git)

**Comment by asarigun** [comment]
You can check it my solution [here](https://github.com/gcorso/DiffDock/issues/44#issuecomment-1888861672)!
