### ISSUE TITLE
RuntimeError: torch.cat(): expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by ShoufaChen** [gcorso/DiffDock#14]
Hello,

Thanks for your awesome work.
I met following error when training model:

```
loading data from memory:  data/cache_torsion/limit0_INDEXtimesplit_no_lig_overlap_train_maxLigSizeNone_H0_recRad15.0_recMax24_esmEmbeddings/heterographs.pkl
Number of complexes:  16271                                                                          
radius protein: mean 35.324798583984375, std 10.894360542297363, max 140.3852081298828
radius molecule: mean 7.464962482452393, std 3.125143051147461, max 28.649322509765625                                                                                                                     
distance protein-mol: mean 12.960723876953125, std 6.1995849609375, max 70.93856811523438
rmsd matching: mean 0.5280884495331837, std 0.5165252914283075, max 6.0405902977233294                                                                                                                     
loading data from memory:  data/cache_torsion/limit0_INDEXtimesplit_no_lig_overlap_val_maxLigSizeNone_H0_recRad15.0_recMax24_esmEmbeddings/heterographs.pkl
Number of complexes:  955                                                                            
radius protein: mean 35.945213317871094, std 11.460107803344727, max 92.777587890625
radius molecule: mean 7.608007431030273, std 3.1059141159057617, max 21.896770477294922
distance protein-mol: mean 13.32070541381836, std 6.682881832122803, max 54.33257293701172
rmsd matching: mean 0.5830034745709728, std 0.6322264833323166, max 5.280259896200438
Model with 20248214 parameters

Starting training...
Run name:  big_score_model
  0%|                                                                                                                                                                             | 0/1017 [00:13<?, ?it/s]
Traceback (most recent call last):
  File "/home/chenshoufa/anaconda3/envs/diffdock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/chenshoufa/anaconda3/envs/diffdock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/chenshoufa/workspace/DiffDock/train.py", line 158, in <module>
    main_function()
  File "/home/chenshoufa/workspace/DiffDock/train.py", line 153, in main_function
    train(args, model, optimizer, scheduler, ema_weights, train_loader, val_loader, t_to_sigma, run_dir)
  File "/home/chenshoufa/workspace/DiffDock/train.py", line 35, in train
    train_losses = train_epoch(model, train_loader, optimizer, device, t_to_sigma, loss_fn, ema_weights)
  File "/home/chenshoufa/workspace/DiffDock/utils/training.py", line 128, in train_epoch
    raise e
  File "/home/chenshoufa/workspace/DiffDock/utils/training.py", line 105, in train_epoch
    tr_pred, rot_pred, tor_pred = model(data)
  File "/home/chenshoufa/anaconda3/envs/diffdock/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenshoufa/anaconda3/envs/diffdock/lib/python3.9/site-packages/torch_geometric/nn/data_parallel.py", line 70, in forward
    outputs = self.parallel_apply(replicas, inputs, None)
  File "/home/chenshoufa/anaconda3/envs/diffdock/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/chenshoufa/anaconda3/envs/diffdock/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/chenshoufa/anaconda3/envs/diffdock/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/chenshoufa/anaconda3/envs/diffdock/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/chenshoufa/anaconda3/envs/diffdock/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenshoufa/workspace/DiffDock/models/score_model.py", line 299, in forward
    global_pred = self.final_conv(lig_node_attr, center_edge_index, center_edge_attr, center_edge_sh, out_nodes=data.num_graphs)
  File "/home/chenshoufa/anaconda3/envs/diffdock/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenshoufa/workspace/DiffDock/models/score_model.py", line 88, in forward
    out = self.batch_norm(out)
  File "/home/chenshoufa/anaconda3/envs/diffdock/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenshoufa/anaconda3/envs/diffdock/lib/python3.9/site-packages/e3nn/nn/_batchnorm.py", line 178, in forward
    torch.cat(new_means, out=self.running_mean)
RuntimeError: torch.cat(): expected a non-empty list of Tensors
```

**Comment by yufengwhy** [comment]
1. find file (name like this) of e3nn in your conda env
~/miniconda3/envs/diffdock_new/lib/python3.9/site-packages/e3nn/nn/_batchnorm.py

2. edit as follows:
```
177         if self.training and not self.instance:
178             if len(new_means) > 0:
179                 torch.cat(new_means, out=self.running_mean)
180             if len(new_vars) > 0:
181                 torch.cat(new_vars, out=self.running_var)
```

**Comment by amorehead** [comment]
I think this issue might be related to the [pull request](https://github.com/gcorso/DiffDock/pull/155) I just opened on this topic.

**Comment by echen1214** [comment]
Can confirm @amorehead's PR also worked to fix this issue
