### ISSUE TITLE
Complex names are int, cannot be concatenated with str.

### ISSUE THREAD

**Issue by yuh8** [gcorso/DiffDock#141]
https://github.com/gcorso/DiffDock/blob/2782769ccde3127c72c47033e26face97958d7c8/utils/inference_utils.py#L184

When running inference with the provided `data/testset_csv.csv`, the following exception has been raised.
`Traceback (most recent call last):
  File "/app/anaconda3/envs/diffdock/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/app/anaconda3/envs/diffdock/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/raw_data/DiffDock/inference.py", line 71, in <module>
    test_dataset = InferenceDataset(out_dir=args.out_dir, complex_names=complex_name_list, protein_files=protein_path_list,
  File "/mnt/raw_data/DiffDock/utils/inference_utils.py", line 185, in __init__
    labels.extend([complex_names[i] + '_chain_' + str(j) for j in range(len(s))])
  File "/mnt/raw_data/DiffDock/utils/inference_utils.py", line 185, in <listcomp>
    labels.extend([complex_names[i] + '_chain_' + str(j) for j in range(len(s))])
TypeError: unsupported operand type(s) for +: 'int' and 'str'`

Upon further investigation, the complex names provided in the csv file are integers which cannot be concatenated with str. 

A potential fix could be replacing https://github.com/gcorso/DiffDock/blob/2782769ccde3127c72c47033e26face97958d7c8/inference.py#L65
with `[name if name is not None or isinstance(name, str) else f"complex_{i}" for i, name in enumerate(complex_name_list)]`

Could you please have a look and fix accordingly?

**Comment by wangzheqi** [comment]
I have the same error

Generating ESM language model embeddings
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  KCX  in the complex. Replacing it with a dash - .
encountered unknown AA:  KCX  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  PTR  in the complex. Replacing it with a dash - .
Traceback (most recent call last):
  File "/public/home/wangzq1992/miniconda3/envs/diffdock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/public/home/wangzq1992/miniconda3/envs/diffdock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/public/home/wangzq1992/DiffDock/DiffDock-main/inference.py", line 71, in <module>
    test_dataset = InferenceDataset(out_dir=args.out_dir, complex_names=complex_name_list, protein_files=protein_path_list,
  File "/public/home/wangzq1992/DiffDock/DiffDock-main/utils/inference_utils.py", line 184, in __init__
    labels.extend([complex_names[i] + '_chain_' + str(j) for j in range(len(s))])
  File "/public/home/wangzq1992/DiffDock/DiffDock-main/utils/inference_utils.py", line 184, in <listcomp>
    labels.extend([complex_names[i] + '_chain_' + str(j) for j in range(len(s))])
TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by YoungjunLee13** [comment]
Same here. Did you resolve the issue?

```
python -m inference --protein_ligand_csv data/testset_csv.csv --out_dir results/user_predictions_testset --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise

Generating ESM language model embeddings
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  KCX  in the complex. Replacing it with a dash - .
encountered unknown AA:  KCX  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  CSO  in the complex. Replacing it with a dash - .
encountered unknown AA:  PTR  in the complex. Replacing it with a dash - .
Traceback (most recent call last):
  File "/home/wyddcaltte3/anaconda3/envs/diffdock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wyddcaltte3/anaconda3/envs/diffdock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wyddcaltte3/DiffDock/inference.py", line 71, in <module>
    test_dataset = InferenceDataset(out_dir=args.out_dir, complex_names=complex_name_list, protein_files=protein_path_list,
  File "/home/wyddcaltte3/DiffDock/utils/inference_utils.py", line 184, in __init__
    labels.extend([complex_names[i] + '_chain_' + str(j) for j in range(len(s))])
  File "/home/wyddcaltte3/DiffDock/utils/inference_utils.py", line 184, in <listcomp>
    labels.extend([complex_names[i] + '_chain_' + str(j) for j in range(len(s))])
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```
