### ISSUE TITLE
Have a problem with installing the openfold

### ISSUE THREAD

**Issue by hyejun18** [gcorso/DiffDock#148]
Hello, I am Hyejun Kim from Seoul National University.
I have a problem when I try to install openfold by command in README of DiffDock.
Do you have any idea how to solve it or what the cause is?

******My Command and Error Messages******

```» pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307'

Collecting openfold@ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307
  Cloning https://github.com/aqlaboratory/openfold.git (to revision 4b41059694619831a7db195b7e0988fc4ff3a307) to /tmp/pip-install-8ypvxotw/openfold_316a05ddadf14b2da164a719fb347f26
  Running command git clone --filter=blob:none --quiet https://github.com/aqlaboratory/openfold.git /tmp/pip-install-8ypvxotw/openfold_316a05ddadf14b2da164a719fb347f26
  Running command git rev-parse -q --verify 'sha^4b41059694619831a7db195b7e0988fc4ff3a307'
  Running command git fetch -q https://github.com/aqlaboratory/openfold.git 4b41059694619831a7db195b7e0988fc4ff3a307
  Running command git checkout -q 4b41059694619831a7db195b7e0988fc4ff3a307
  Resolved https://github.com/aqlaboratory/openfold.git to commit 4b41059694619831a7db195b7e0988fc4ff3a307
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8ypvxotw/openfold_316a05ddadf14b2da164a719fb347f26/setup.py", line 56, in <module>
          _, bare_metal_major, _ = get_cuda_bare_metal_version(CUDA_HOME)
        File "/tmp/pip-install-8ypvxotw/openfold_316a05ddadf14b2da164a719fb347f26/setup.py", line 40, in get_cuda_bare_metal_version
          raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
      TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.```

**Comment by HanMengying** [comment]
It seems that you didn't have the cuda. Input the command "nvcc -V" to make sure you have the cuda. Until you can print the cuda_dir in your python.

**Comment by hyejun18** [comment]
Oh I usually use cuda in conda env., so I didn't notice that there is no cuda in diffdock conda env. Thank you!!

**Comment by HanMengying** [comment]
No problem.Have a good day!!
