### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by xavierchee** [gcorso/DiffDock#158]
Dear team, i tried the code below

pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric==2.0.4 -f https://data.pyg.org/whl/torch-1.11.0+cu117.html

but i got the following error

```
Looking in links: https://data.pyg.org/whl/torch-1.11.0+cu117.html
Collecting torch-scatter
  Downloading torch_scatter-2.1.1.tar.gz (107 kB)
     ━━━━━━ 107.6… 293.0  eta 0:00:…            kB     kB/s
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-xoyuok97/torch-scatter_7c421c32c3a149f494076261388a8d34/setup.py", line 8, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
(conda_diffdock) [xchee@tooarrana2 ~]$ y
-bash: y: command not found
(conda_diffdock) [xchee@tooarrana2 ~]$ pip install torch-scatter
Collecting torch-scatter
  Using cached torch_scatter-2.1.1.tar.gz (107 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-2rumn0s2/torch-scatter_4a11d908fe734a9ca1e8ecd7775264a6/setup.py", line 8, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

When i checked the website (https://data.pyg.org/whl/torch-1.11.0+cu117.html), i get the error below. 

403 Forbidden
Code: AccessDenied
Message: Access Denied
RequestId: 2P7A8Q3WDDZ03HF0
HostId: uRqkIXEI53EWTP/21KFBKIciDR2UEol8U5sD8yB6OSQtDRJgsaoPA8b6CY1KT200SKF6NFMgB+A=

Can i know how i should resolve this?
Thanks!

**Comment by asarigun** [comment]
You can check it my solution [here](https://github.com/gcorso/DiffDock/issues/44#issuecomment-1888861672)

**Comment by sherryliu987** [comment]
If you're struggling to install DiffDock locally, feel free to try https://www.tamarind.bio/, a website which offers a no-code interface for bioinformatics tools including docking tools like DiffDock and AutoDock.
