### ISSUE TITLE
Installation error - GLIBC_2.34 related

### ISSUE THREAD

**Issue by Huanle** [gcorso/DiffDock#174]
Hi @gcorso ,

Thanks heaps for bringing **diffdock** to the community. 

I was struggling with the installation of this program.

It seemed to be ok until I started to run the example command. 

command:
```
python -m inference --protein_ligand_csv data/protein_ligand_example_csv.csv --out_dir results/user_predictions_small --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise
```

Error message:
<Traceback (most recent call last):
  File "/home/huanle/miniconda3/envs/diffdock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/huanle/miniconda3/envs/diffdock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/huanle/sw/structual_bioinformatics/protein_nucleotides/DiffDock-main/inference.py", line 10, in <module>
    from torch_geometric.loader import DataLoader
  File "/home/huanle/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/huanle/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/huanle/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_geometric/data/data.py", line 9, in <module>
    from torch_sparse import SparseTensor
  File "/home/huanle/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_sparse/__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/huanle/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch/_ops.py", line 220, in load_library
    ctypes.CDLL(path)
  File "/home/huanle/miniconda3/envs/diffdock/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/popular/hl_miniconda3/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_sparse/_version_cpu.so)
(diffdock) huanle@node1:~/.../DiffDock-main$ vi /home/huanle/miniconda3/envs/diffdock/lib/python3.9/ctypes/__init__.py
>

The error message indicates that the GLBC_2.34 is missing though I think it is installed. 
Because this `strings /home/popular/hl_miniconda3/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_sparse/_version_cpu.so | grep GLIB`
yields:
<GLIBC_2.34
GLIBC_2.4
GLIBC_2.2.5
GLIBCXX_3.4.9
GLIBCXX_3.4>

Can you help me fix this problem? Thanks a lot!

**Comment by asarigun** [comment]
You can check my solution [here](https://github.com/gcorso/DiffDock/issues/44#issuecomment-1888861672)!

**Comment by sherryliu987** [comment]
If you're struggling to install DiffDock locally, feel free to try https://www.tamarind.bio/, a website which offers a no-code interface for bioinformatics tools including docking tools like DiffDock and AutoDock.
