### ISSUE TITLE
Failure due to a shape mismatch by inference.py

### ISSUE THREAD

**Issue by yukisoya** [gcorso/DiffDock#189]
I executed the following command in a container created from the provided Dockerfile:

```bash
micromamba run -n diffdock python -m inference --config default_inference_args.yaml --protein_ligand_csv data/testset_csv_2.csv --out_dir results/user_predictions_small
```

The testset_csv_2.csv used for inference contains the following data:
>complex_name,protein_path,ligand_description,protein_sequence
>0,data/PDBBind_processed/6qqw/6qqw_protein_processed.pdb,data/PDBBind_processed/6qqw/6qqw_ligand.mol2,

In addition, I've made a modification to the inference_utils.py script to ensure proper handling of the complex_name column in the CSV file. Initially, I encountered an error when the complex_name values were integers. To resolve this, I edited the line 159 in inference_utils.py to `labels.extend([str(complex_names[i]) + '_chain_' + str(j) for j in range(len(s))])`.

However, I encountered a tensor shape mismatch error during the computation, as detailed in the output below:

> DiffDock will run on cuda
> Generating ESM language model embeddings
> /home/appuser/micromamba/envs/diffdock/lib/python3.9/site-packages/torch/cuda/__init__.py:155: UserWarning: 
> NVIDIA H100 80GB HBM3 with CUDA capability sm_90 is not compatible with the current PyTorch installation.
> The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75 sm_80 sm_86.
> If you want to use the NVIDIA H100 80GB HBM3 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
> 
> Processing 1 of 1 batches (2 sequences)
> HAPPENING | confidence model uses different type of graphs than the score model. Loading (or creating if not existing) the data for the confidence model now.
> /home/appuser/micromamba/envs/diffdock/lib/python3.9/site-packages/torch/jit/_check.py:181: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
> 
> Size of test dataset:  1
> 0it [00:00, ?it/s]@> 6214 atoms and 1 coordinate set(s) were parsed in 0.03s.
> /home/appuser/DiffDock/datasets/parse_chi.py:91: RuntimeWarning: invalid value encountered in cast
>   Y = indices.astype(int)
> @> 6214 atoms and 1 coordinate set(s) were parsed in 0.03s.
> Failed on tensor([0]) shape mismatch: value tensor of shape [196] cannot be broadcast to indexing result of shape [88]
> 1it [00:00,  1.62it/s]
> Failed for 1 complexes
> Skipped 0 complexes
> Results are in results/user_predictions_small

I'm seeking help to resolve the tensor shape mismatch issue. Any advice on how to adjust the input data or modify the inference settings to prevent this error would be greatly appreciated.

Thank you for your support!

**Comment by gcorso** [comment]
Hi @yukisoya could you check whether the issue is still there with the fixes of the recent commits?

**Comment by aolgac** [comment]
Dear Gabriele,

I hope this message finds you well. I am encountering issues while running the DiffDock-L model, which seem similar to the problem described in Issue #189. Below is a summary of the errors I am facing:

/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/site-packages/torch/cuda/__init__.py:155: UserWarning:  
NVIDIA H100 with CUDA capability sm_90 is not compatible with the current PyTorch installation.  
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75 sm_80 sm_86.
If you want to use the NVIDIA H100 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
^M0it [00:00, ?it/s]/home/aolgac/Programs/DiffDock/datasets/parse_chi.py:91: RuntimeWarning: invalid value encountered in cast
  Y = indices.astype(int)
--- Logging error ---
Traceback (most recent call last):
  File "/home/aolgac/Programs/DiffDock/inference.py", line 260, in main
    data_list, confidence = sampling(data_list=data_list, model=model,
  File "/home/aolgac/Programs/DiffDock/utils/sampling.py", line 108, in sampling
    crop_beyond(batch, tr_sigma * 3 + model_args.crop_beyond, model_args.all_atoms)
  File "/home/aolgac/Programs/DiffDock/utils/utils.py", line 405, in crop_beyond
    subgraph(residues_to_keep, complex_graph['receptor', 'rec_contact', 'receptor'].edge_index, relabel_nodes=True)[0]
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/site-packages/torch_geometric/utils/subgraph.py", line 105, in subgraph
    node_idx[subset] = torch.arange(subset.sum().item(), device=device)
RuntimeError: shape mismatch: value tensor of shape [217] cannot be broadcast to indexing result of shape [133]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/aolgac/Programs/DiffDock/inference.py", line 318, in <module>
  File "/home/aolgac/Programs/DiffDock/inference.py", line 302, in main
    logger.warning("Failed on", orig_complex_graph["name"], e)
Message: 'Failed on'
Arguments: (['1a0q'], RuntimeError('shape mismatch: value tensor of shape [217] cannot be broadcast to indexing result of shape [133]'))
^M1it [00:00,  1.71it/s]--- Logging error ---
Traceback (most recent call last):
  File "/home/aolgac/Programs/DiffDock/inference.py", line 260, in main
    data_list, confidence = sampling(data_list=data_list, model=model,
  File "/home/aolgac/Programs/DiffDock/utils/sampling.py", line 116, in sampling
    tr_score, rot_score, tor_score = model(mod_complex_graph_batch)[:3]
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aolgac/Programs/DiffDock/models/cg_model.py", line 318, in forward
    rec_edge_index, rec_edge_attr, rec_edge_sh, rec_edge_weight = self.embedding(data)
  File "/home/aolgac/Programs/DiffDock/models/cg_model.py", line 290, in embedding
    rec_node_attr = self.rec_emb_layers[l](rec_node_attr, data['receptor', 'receptor'].edge_index, edge_attr_, rec_edge_sh, edge_weight=rec_edge_weight)
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aolgac/Programs/DiffDock/models/tensor_layers.py", line 311, in forward
    raise ValueError("No edges and no nodes")
ValueError: No edges and no nodes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/aolgac/Programs/DiffDock/inference.py", line 318, in <module>
    main(_args)
  File "/home/aolgac/Programs/DiffDock/inference.py", line 302, in main
    logger.warning("Failed on", orig_complex_graph["name"], e)
Message: 'Failed on'
Arguments: (['1a0q'], RuntimeError('shape mismatch: value tensor of shape [217] cannot be broadcast to indexing result of shape [133]'))
^M1it [00:00,  1.71it/s]--- Logging error ---
Traceback (most recent call last):
  File "/home/aolgac/Programs/DiffDock/inference.py", line 260, in main
    data_list, confidence = sampling(data_list=data_list, model=model,
  File "/home/aolgac/Programs/DiffDock/utils/sampling.py", line 116, in sampling
    tr_score, rot_score, tor_score = model(mod_complex_graph_batch)[:3]
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aolgac/Programs/DiffDock/models/cg_model.py", line 318, in forward
    rec_edge_index, rec_edge_attr, rec_edge_sh, rec_edge_weight = self.embedding(data)
  File "/home/aolgac/Programs/DiffDock/models/cg_model.py", line 290, in embedding
    rec_node_attr = self.rec_emb_layers[l](rec_node_attr, data['receptor', 'receptor'].edge_index, edge_attr_, rec_edge_sh, edge_weight=rec_edge_weight)
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aolgac/Programs/DiffDock/models/tensor_layers.py", line 311, in forward
    raise ValueError("No edges and no nodes")
ValueError: No edges and no nodes
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/aolgac/Softwares/venvs/diffdock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/aolgac/Programs/DiffDock/inference.py", line 318, in <module>
    main(_args)
  File "/home/aolgac/Programs/DiffDock/inference.py", line 302, in main
    logger.warning("Failed on", orig_complex_graph["name"], e)
Message: 'Failed on'
Arguments: (['1a0q_custom'], ValueError('No edges and no nodes'))
^M2it [00:01,  1.92it/s]^M2it [00:01,  1.89it/s]
[2024-Nov-28 13:17:40 CET] WARNING -
    Failed for 2 / 2 complexes.
    Skipped 0 / 2 complexes.

I have verified that my installation aligns with the guidelines provided in the DiffDock documentation, but the errors persist.

Moreover, I noticed that a [similar problem was reported in Issue #237](https://github.com/gcorso/DiffDock/issues/237), particularly the "No edges and no nodes" error, which might be related.

I am currently using an NVIDIA H100 GPU (sm_90) with DiffDock 1.1.3.

Would you be able to confirm whether these errors might share the same underlying cause as described in this issue? If so, could you provide guidance on resolving them or point to any recent updates addressing similar problems?

Thank you for your time and support. I appreciate your efforts in developing and maintaining this excellent solution. I would like to mention that I have achieved remarkable results using DiffDock in my research. Its capabilities have significantly contributed to my work, and I am currently preparing manuscripts that I hope to publish soon. Thank you for creating such an impactful tool for the community!
