### ISSUE TITLE
Question on how to use the evaluate.py 

### ISSUE THREAD

**Issue by starwingc** [gcorso/DiffDock#194]
Hi I have some issue when trying to run the evaluate.py. This is my commend: 

python -m evaluate --config default_inference_args.yaml --complex_name DD_5R7Y_TC5_100_test --protein_path data/5r7y_rec.pdb --ligand_description data/TC5.sdf --out_dir results/user_predictions_small

And the error is:
```
Traceback (most recent call last):
  File "/home/tur54445/work/anaconda3_2023/envs/diffdock-gpu/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tur54445/work/anaconda3_2023/envs/diffdock-gpu/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs/work/tur54445/git/DiffDock/evaluate.py", line 12, in <module>
    resource.setrlimit(resource.RLIMIT_NOFILE, (64000, rlimit[1]))
ValueError: current limit exceeds maximum limit
```

**Comment by starwingc** [comment]
> Hi, the evaluate.py file is to run the model on some of the standard datasets, to run individual predictions please use the inference.py file

Thanks!
