### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'origin'

### ISSUE THREAD

**Issue by entropybit** [gcorso/DiffDock#21]
However I try to use diffdock ( I followed the instructions with creating the conda environment and all that seemed to work) 
I'll get the error mentioned in the title. To be more specific it looks like this.

```
$ python -m inference --protein_ligand_csv data/protein_ligand_example_csv.csv --out_dir results/user_predictions_small --inference_steps 20 --samples_per_complex 40 --batch_size 10

Traceback (most recent call last):
  File "/work/scratch/b_mayer/miniconda3/envs/diffdock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/scratch/b_mayer/miniconda3/envs/diffdock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/work/scratch/b_mayer/DiffDock/inference.py", line 16, in <module>
    from datasets.pdbbind import PDBBind
  File "/work/scratch/b_mayer/DiffDock/datasets/pdbbind.py", line 22, in <module>
    from utils.utils import read_strings_from_txt
  File "/work/scratch/b_mayer/DiffDock/utils/utils.py", line 12, in <module>
    from torch_geometric.nn.data_parallel import DataParallel
  File "/work/scratch/b_mayer/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_geometric/nn/__init__.py", line 3, in <module>
    from .sequential import Sequential
  File "/work/scratch/b_mayer/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_geometric/nn/sequential.py", line 8, in <module>
    from torch_geometric.nn.conv.utils.jit import class_from_module_repr
  File "/work/scratch/b_mayer/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_geometric/nn/conv/__init__.py", line 25, in <module>
    from .spline_conv import SplineConv
  File "/work/scratch/b_mayer/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_geometric/nn/conv/spline_conv.py", line 16, in <module>
    from torch_spline_conv import spline_basis, spline_weighting
  File "/work/scratch/b_mayer/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_spline_conv/__init__.py", line 11, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
AttributeError: 'NoneType' object has no attribute 'origin'_
```

I found that if I open a python console in the DiffDock folder and do 
```from datasets.pdbbind import PDBBind``` I'll get the same error as above:

```
>>>from datasets.pdbbind import PDBBind
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/scratch/b_mayer/DiffDock/datasets/pdbbind.py", line 22, in <module>
    from utils.utils import read_strings_from_txt
  File "/work/scratch/b_mayer/DiffDock/utils/utils.py", line 12, in <module>
    from torch_geometric.nn.data_parallel import DataParallel
  File "/work/scratch/b_mayer/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_geometric/nn/__init__.py", line 3, in <module>
    from .sequential import Sequential
  File "/work/scratch/b_mayer/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_geometric/nn/sequential.py", line 8, in <module>
    from torch_geometric.nn.conv.utils.jit import class_from_module_repr
  File "/work/scratch/b_mayer/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_geometric/nn/conv/__init__.py", line 25, in <module>
    from .spline_conv import SplineConv
  File "/work/scratch/b_mayer/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_geometric/nn/conv/spline_conv.py", line 16, in <module>
    from torch_spline_conv import spline_basis, spline_weighting
  File "/work/scratch/b_mayer/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_spline_conv/__init__.py", line 11, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
AttributeError: 'NoneType' object has no attribute 'origin'
```

**Comment by cjvsimoes** [comment]
I'm getting the same error (issue title) on a HPC cluster, and when I reach the import of PDBbind datasets on a python console I get the following error: 

/diffdock_directory/utils/torus.py:38: RuntimeWarning: invalid value encountered in divide
  score_ = grad(x, sigma[:, None], N=100) / p_

**Comment by entropybit** [comment]
@cjvsimoes I also encountered this while trying to get it to run on a cluster. Its a RedHat 8.5 based cluster with 96 AVX512 cores, although I don't see how this should make a difference for a conda based installation.

**Comment by gcorso** [comment]
Hi,
The issue seems to lie with `torch_geometric` installation (very common), could you try to uninstall it and reinstall it? 
In particular, make sure that the CUDA version on the GPU that you are using, is compatible of the cuda toolkit installed as part of pytorch and that the cuda toolkit version is the same as the one torch geometric is installed for.

**Comment by cjvsimoes** [comment]
Hi,
On my side, the issue seems to be resolved. Reinstalling torch_geometric, alone, didn't do the trick; loading the appropriate CUDA modules did (available at the HPC cluster).

**Comment by gcorso** [comment]
Ok thanks for the update. I'll close the issue for now

**Comment by entropybit** [comment]
Didn't have the time yet to look into it at our cluster but this probably will also solve it, I thought the packages will install their own cuda version via dependencies or something, that was a little bit naive of me. It will probably be solved by just redoing the installation after loading a cude version from our module system. I'll report how that went as soon as I'll be able to get to ti.
In any case thanks for the fix.

**Comment by gcorso** [comment]
Yeah that is always my hope, but, unfortunately, I have often experienced it not being the case for pytorch geometric
