### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './workdir/v1.1/score_model/model_parameters.yml'

### ISSUE THREAD

**Issue by rytakahashi** [gcorso/DiffDock#210]
Just to run posebusters benchmark, 

```
python -m evaluate  --config default_inference_args.yaml --data_dir data/posebusters_benchmark_set --tqdm --dataset posebusters --split_path data/splits/posebusters_benchmark_set_ids.txt --esm_embeddings_path data/posebusters_ESM.pt --chain_cutoff 10 --batch_size 10 --protein_file protein --ligand_file ligands --save_visualisation

  _exp_score_norms = np.sqrt(np.sum(_score_norms**2 * _pdf_vals, axis=1) / np.sum(_pdf_vals, axis=1) / np.pi)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:42<00:00,  4.73it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:58<00:00,  3.46it/s]
/home/rtakahashi/software/DiffDock/utils/torus.py:38: RuntimeWarning: invalid value encountered in divide
  score_ = grad(x, sigma[:, None], N=100) / p_
Traceback (most recent call last):
  File "/home/rtakahashi/mambaforge/envs/diffdock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/rtakahashi/mambaforge/envs/diffdock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rtakahashi/software/DiffDock/evaluate.py", line 199, in <module>
    with open(f'{args.model_dir}/model_parameters.yml') as f:
FileNotFoundError: [Errno 2] No such file or directory: './workdir/v1.1/score_model/model_parameters.yml'

```
How to generate model_parameters.yml or can I download it?

Thanks,

**Comment by rytakahashi** [comment]
never mind, as documented v1.0.

**Comment by AustinApple** [comment]
Hello @rytakahashi,
I have the same issue of finding the directory of workdir. Where did you find it?

Thanks
