### ISSUE TITLE
Problem with openfold installation. 

### ISSUE THREAD

**Issue by zeqri** [gcorso/DiffDock#217]
Hi, 

I was able to install all packages required except for openfold. When trying to install it keep running into this error: 

  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/gpfs/bwfor/scratch/fr_ma453_o05i14/pip-req-build-qo0kbx1r/setup.py", line 56, in <module>
          _, bare_metal_major, _ = get_cuda_bare_metal_version(CUDA_HOME)
        File "/gpfs/bwfor/scratch/fr_ma453_o05i14/pip-req-build-qo0kbx1r/setup.py", line 40, in get_cuda_bare_metal_version
          raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
      TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details. 

If someone could give feedback on how to solve this issue I would highly appreciate it.

**Comment by tornikeo** [comment]
Most likely you need to install cudatoolkit, using conda, or micromamba, like so:

```
micromamba install cudatoolkit -c nvidia
```

You get ` TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'` since `cuda_dir` gives a None unless you have cudatoolkit, which contains the `nvcc`. Hope this  helps.

**Comment by ejmeitz** [comment]
I had to install `cudatoolkit-dev`.

You can also check this specific issue by opening python and:
```
from torch.utils.cpp_extension import CUDA_HOME
 print(CUDA_HOME)
```
