### ISSUE TITLE
istallation problem/ running interface python : No module named 'torch' (How to install torch and its dependecies properly?)

### ISSUE THREAD

**Issue by sajad-stack** [gcorso/DiffDock#225]
Hi,

I followed the readme to install the DiffDock-L as follows:
conda env create --file environment.yml
conda activate diffdock

However, when I tried running the "interface" python I faced the following error.
Could you provide some guidance on how to fix this issue?

Thank you

python -m inference --config default_inference_args.yaml  --protein_ligand_csv data/protein_ligand_example.csv --out_dir results/user_predictions_small 
Traceback (most recent call last):
  File "/home/sajad/mambaforge/envs/diffdock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sajad/mambaforge/envs/diffdock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/sajad/WD/E/Tools/DiffDock-L/DiffDock/inference.py", line 20, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by tornikeo** [comment]
Means you don't have [this package ](https://pytorch.org/get-started/locally/). Follow it, while inside that `diffdock` environment that you created.

You'll also need to have a recent-enough GPU to run this in reasonable time.
