### ISSUE TITLE
_LinAlgErr when running inference

### ISSUE THREAD

**Issue by ingcoder** [gcorso/DiffDock#227]
Hi, I'm using the latest version of DiffDock (1.1.2) on an M1 architecture and encountering an error during inference on a PDB file with two protein chains. The issue seems related to how the 'rot_perturb' tensor is generated, which occasionally includes NaN values. Sometimes the code works, and other times it doesn't.

Has anyone else experienced this problem and knows how to resolve it?

The error I believe originates in line 131 in sampling.py, producing the following tensor.

`tr_z = torch.zeros((min(batch_size, N), 3), device=device) if no_random or (no_final_step_noise and t_idx == inference_steps - 1) \
                        else torch.normal(mean=0, std=1, size=(min(batch_size, N), 3), device=device)
                    tr_perturb = (tr_g ** 2 * dt_tr * tr_score + tr_g * np.sqrt(dt_tr) * tr_z)

                    rot_z = torch.zeros((min(batch_size, N), 3), device=device) if no_random or (no_final_step_noise and t_idx == inference_steps - 1) \
                        else torch.normal(mean=0, std=1, size=(min(batch_size, N), 3), device=device)
                    rot_perturb = (rot_score * dt_rot * rot_g ** 2 + rot_g * np.sqrt(dt_rot) * rot_z)`

rot_perturb

` tensor([[    nan,     nan,     nan],
        [-0.2149, -0.4666,  0.6783],
        [-0.5220, -1.0061,  1.4471],
        [ 0.2730,  0.3447,  0.6063],
        [-0.5929, -0.0834,  0.1056],
        [ 0.7658,  0.0830,  0.3789],
        [-0.0545,  2.1462, -0.7180],
        [ 0.3357, -0.7509,  0.6988],
        [-1.3578,  0.5666, -1.8663],
        [-1.2711,  1.3159,  1.0550]])
`

Resulting in runtime error:

```
Traceback (most recent call last):
  File "/DiffDock/inference.py", line 262, in main
    data_list, confidence = sampling(data_list=data_list, model=model,
  File "/DiffDock/utils/sampling.py", line 178, in sampling
    modify_conformer_batch(complex_graph_batch['ligand'].pos, complex_graph_batch, tr_perturb, rot_perturb,
  File "/DiffDock/utils/diffusion_utils.py", line 73, in modify_conformer_batch
    R, t = rigid_transform_Kabsch_3D_torch_batch(flexible_new_pos, rigid_new_pos)
  File "/DiffDock/utils/geometry.py", line 267, in rigid_transform_Kabsch_3D_torch_batch
    U, S, Vt = torch.linalg.svd(H)
torch._C._LinAlgError: linalg.svd: (Batch element 0): The algorithm failed to converge because the input matrix contained non-finite values.

**Comment by srilekha1993** [comment]
@ingcoder  yes there is a variation of output in the code.

**Comment by ingcoder** [comment]
@srilekha1993 . Thank you. Do you know what is causing this error and if this bug is going to be fixed?
