### ISSUE TITLE
Different Failed on complexes for inference.py on CPU and GPU are different for different batch size

### ISSUE THREAD

**Issue by srilekha1993** [gcorso/DiffDock#229]
Hi, 
I have tried running on 363 complexes given on testset_csv.csv. But getting failed cases on CPU are 21 complexes and 
on GPU are 16 complexes (CUDA out of memory)
And 6hlb: which is not available in test data
As our aim to check the CPU and GPU time comparison of the sets which are not showing any failed cases.
So we again tested for CPU by removing 21 complexes but get again 14 failed cases(complexes) and after removing those 14 complexes get 16 complexes failed.
For GPU , after removing 16 complexes we successfully run the rest complexes without any failed cases.
The above experiments for **(batch_size=10)**

 For batch_size = 1, For GPU get 29 failed complexes and for CPU Failed for 30 complexes. Got the error like below
"""" Failed on ['6mjj'] linalg.svd: (Batch element 2): The algorithm failed to converge because the input matrix contained non-finite values.
""""
Please let us know what is the reason behind this as we are getting different failed cases on cpu and gpu and for different batch size

**Comment by srilekha1993** [comment]
@gcorso Please clarify on above issue

**Comment by jsilter** [comment]
Could you try again with the most recent version?

**Comment by srilekha1993** [comment]
sure

**Comment by srilekha1993** [comment]
Hi @jsilter,
I have run the current version of Diffdock on 363 complexes mentioned in testset_csv for batch size=10, getting the failing for 5 complexes
While running for batch size=1 getting few exceptions, pasting below for one of the iteration
48it [49:44, 25.37s/it]--- Logging error ---
Traceback (most recent call last):
  File "/home/hgx/omics/srilekhx/DiffDock-1.1.2/inference.py", line 261, in main
    data_list, confidence = sampling(data_list=data_list, model=model,
  File "/home/hgx/omics/srilekhx/DiffDock-1.1.2/utils/sampling.py", line 115, in sampling
    tr_score, rot_score, tor_score = model(mod_complex_graph_batch)[:3]
  File "/data/sudarsh2/miniconda3/envs/diff_L_new_rec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/sudarsh2/miniconda3/envs/diff_L_new_rec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hgx/omics/srilekhx/DiffDock-1.1.2/models/cg_model.py", line 318, in forward
    rec_edge_index, rec_edge_attr, rec_edge_sh, rec_edge_weight = self.embedding(data)
  File "/home/hgx/omics/srilekhx/DiffDock-1.1.2/models/cg_model.py", line 290, in embedding
    rec_node_attr = self.rec_emb_layers[l](rec_node_attr, data['receptor', 'receptor'].edge_index, edge_attr_, rec_edge_sh, edge_weight=rec_edge_weight)
  File "/data/sudarsh2/miniconda3/envs/diff_L_new_rec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/sudarsh2/miniconda3/envs/diff_L_new_rec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hgx/omics/srilekhx/DiffDock-1.1.2/models/tensor_layers.py", line 311, in forward
    raise ValueError("No edges and no nodes")
ValueError: No edges and no nodes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/sudarsh2/miniconda3/envs/diff_L_new_rec/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/data/sudarsh2/miniconda3/envs/diff_L_new_rec/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/data/sudarsh2/miniconda3/envs/diff_L_new_rec/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/data/sudarsh2/miniconda3/envs/diff_L_new_rec/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/data/sudarsh2/miniconda3/envs/diff_L_new_rec/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/sudarsh2/miniconda3/envs/diff_L_new_rec/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hgx/omics/srilekhx/DiffDock-1.1.2/inference.py", line 319, in <module>
    main(_args)
  File "/home/hgx/omics/srilekhx/DiffDock-1.1.2/inference.py", line 303, in main
    logger.warning("Failed on", orig_complex_graph["name"], e)
Message: 'Failed on'
Arguments: (['6ott'], ValueError('No edges and no nodes'))



Please let me know what is could be the issue for getting different results for different batch size on inference.py on pdbbind dataset

**Comment by srilekha1993** [comment]
Hi @jsilter,
As per your suggestion we have run the most recent version of Diffdock-1.1.2
So while executing inference.py on **GPU** we are getting **0 failed cases** and 5 skipped 

but for **CPU** execution we are getting different number of failed cases for different runs. The error pasted below
--- Logging error ---
Traceback (most recent call last):
  File "/home/hgx/omics/srilekhx/Diffdock_1.1.2_mod/inference.py", line 260, in main
    data_list, confidence = sampling(data_list=data_list, model=model,
  File "/home/hgx/omics/srilekhx/Diffdock_1.1.2_mod/utils/sampling.py", line 190, in sampling
    modify_conformer_batch(complex_graph_batch['ligand'].pos, complex_graph_batch, tr_perturb, rot_perturb,
  File "/home/hgx/omics/srilekhx/Diffdock_1.1.2_mod/utils/diffusion_utils.py", line 73, in modify_conformer_batch
    R, t = rigid_transform_Kabsch_3D_torch_batch(flexible_new_pos, rigid_new_pos)
  File "/home/hgx/omics/srilekhx/Diffdock_1.1.2_mod/utils/geometry.py", line 266, in rigid_transform_Kabsch_3D_torch_batch
    U, S, Vt = torch.linalg.svd(H)
torch._C._LinAlgError: linalg.svd: (Batch element 2): The algorithm failed to converge because the input matrix contained non-finite values.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/sudarsh2/miniconda3/envs/diff_L_new_rec/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/data/sudarsh2/miniconda3/envs/diff_L_new_rec/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/data/sudarsh2/miniconda3/envs/diff_L_new_rec/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/data/sudarsh2/miniconda3/envs/diff_L_new_rec/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/data/sudarsh2/miniconda3/envs/diff_L_new_rec/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/sudarsh2/miniconda3/envs/diff_L_new_rec/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hgx/omics/srilekhx/Diffdock_1.1.2_mod/inference.py", line 318, in <module>
    main(_args)       
File "/home/hgx/omics/srilekhx/Diffdock_1.1.2_mod/inference.py", line 302, in main
    logger.warning("Failed on", orig_complex_graph["name"], e)
Message: 'Failed on'
Arguments: (['6seo'], _LinAlgError('linalg.svd: (Batch element 2): The algorithm failed to converge because the input matrix contained non-finite values.'))

The complexes which are getting failed when we are trying individually its getting executed successfully.

Can you please let us know the reason behind the variation of output.
