### ISSUE TITLE
ValueError: Bad Conformer ID

### ISSUE THREAD

**Issue by thomasvargo** [gcorso/DiffDock#27]
I saw issue#13 was very similar, but this doesn't seem to be the same problem.  I have the updated version of the pdbbind.py.
 

```
Reading molecules and generating local structures with RDKit
 75%|█████████████████████████████▎         | 2315/3080 [01:20<00:18, 42.04it/s]rdkit coords could not be generated without using random coords. using random coords now.
 75%|█████████████████████████████▎         | 2317/3080 [02:35<00:51, 14.90it/s]
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/diffdock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/miniconda3/envs/diffdock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/DiffDock/inference.py", line 81, in <module>
    test_dataset = PDBBind(transform=None, root='', protein_path_list=protein_path_list, ligand_descriptions=ligand_descriptions,
  File "/home/ubuntu/DiffDock/datasets/pdbbind.py", line 102, in __init__
    self.inference_preprocessing()
  File "/home/ubuntu/DiffDock/datasets/pdbbind.py", line 203, in inference_preprocessing
    generate_conformer(mol)
  File "/home/ubuntu/DiffDock/datasets/process_mols.py", line 276, in generate_conformer
    AllChem.MMFFOptimizeMolecule(mol, confId=0)
ValueError: Bad Conformer Id
```

**Comment by cjvsimoes** [comment]
I second thomasvargo here:

Traceback (most recent call last):
  File "/[omitted]/miniconda3/envs/diffdock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/[omitted]/miniconda3/envs/diffdock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/[omitted]/DiffDock/RUN1c/inference.py", line 81, in <module>
    test_dataset = PDBBind(transform=None, root='', protein_path_list=protein_path_list, ligand_descriptions=ligand_descriptions,
  File "/[omitted]/DiffDock/RUN1c/datasets/pdbbind.py", line 102, in __init__
    self.inference_preprocessing()
  File "/[omitted]/DiffDock/RUN1c/datasets/pdbbind.py", line 210, in inference_preprocessing
    generate_conformer(mol)
  File "/[omitted]/DiffDock/RUN1c/datasets/process_mols.py", line 276, in generate_conformer
    AllChem.MMFFOptimizeMolecule(mol, confId=0)
ValueError: Bad Conformer Id

**Comment by thomasvargo** [comment]
This happened again.  Looking at the molecules that caused the error there were 3 that all contained the same substructure: Nc1ccc(S(=O)(=O)F)cc1
not sure if that helps

**Comment by HannesStark** [comment]
Could you please share one of the files or SMILES for which this is happening?

**Comment by thomasvargo** [comment]
Hi Hannes, 
Thanks for looking into this!  I’ll try to find a ligand that I can share.  
Note: 
I’m running it on AWS EC2 box with a gpu.
--
Thomas Vargo
Medicinal Chemist - PostEra
Mobile: 978-846-2472

**Comment by thomasvargo** [comment]
Thanks for looking into this!  I will amend my previous statement.  it wasn't the sulfonylfluoride.  I isolated it to a different part of the molecule.  I can't give you the whole molecule, but this fragment also causes the same problem:
`CNC(=O)N1[C@@H]2CCC[C@@H]1CC2 |&1:5,9|`

**Comment by HannesStark** [comment]
Hi, sorry for the delay.

Unfortunately, it seems that RDKIT cannot generate a 3D structure for your molecule.
I gather this from the following discussion: https://github.com/rdkit/rdkit/issues/2996#issuecomment-1298798758

Maybe your smiles does not actually have a physically plausible 3D structure.
<img width="165" alt="image" src="https://user-images.githubusercontent.com/32128654/202914684-3abba1ce-e4f0-44e9-944f-408a42bf54fe.png">
