### ISSUE TITLE
Unrecognized argument ligand_path

### ISSUE THREAD

**Issue by duerrsimon** [gcorso/DiffDock#3]
Seems the instructions in the README are wrong because `--ligand_path` does not exist. I tried using --ligand but that throws a different error. 
```
python -m inference --ligand_path examples/1cbr_ligand.sdf --protein_path examples/1cbr_protein.pdb --out_dir results/user_predictions_small --inference_steps 20 --samples_per_complex 40 --batch_size 10
100%|████████████████████████████████████████████████████████████████████████████████████████| 201/201 [01:33<00:00,  2.14it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████| 201/201 [02:04<00:00,  1.61it/s]
/share/lcbcsrv5/lcbcdata/duerr/PhD/08_Code/DiffDock/utils/torus.py:38: RuntimeWarning: invalid value encountered in divide
  score_ = grad(x, sigma[:, None], N=100) / p_
usage: inference.py [-h] [--config CONFIG] [--protein_ligand_csv PROTEIN_LIGAND_CSV] [--protein_path PROTEIN_PATH]
                    [--ligand LIGAND] [--out_dir OUT_DIR] [--esm_embeddings_path ESM_EMBEDDINGS_PATH] [--save_visualisation]
                    [--samples_per_complex SAMPLES_PER_COMPLEX] [--model_dir MODEL_DIR] [--ckpt CKPT]
                    [--confidence_model_dir CONFIDENCE_MODEL_DIR] [--confidence_ckpt CONFIDENCE_CKPT]
                    [--batch_size BATCH_SIZE] [--cache_path CACHE_PATH] [--no_random] [--no_final_step_noise] [--ode]
                    [--inference_steps INFERENCE_STEPS] [--num_workers NUM_WORKERS] [--sigma_schedule SIGMA_SCHEDULE]
                    [--actual_steps ACTUAL_STEPS] [--keep_local_structures]
inference.py: error: unrecognized arguments: --ligand_path examples/1cbr_ligand.sdf
```

Error with `--ligand`

```
python -m inference --ligand examples/1cbr_ligand.sdf --protein_path examples/1cbr_protein.pdb --out_dir results/user_predictions_small --inference_steps 20 --samples_per_complex 40 --batch_size 10
Reading molecules and generating local structures with RDKit
  0%|                                                                                                    | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/duerr/miniconda3/envs/diffdock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/duerr/miniconda3/envs/diffdock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/share/lcbcsrv5/lcbcdata/duerr/PhD/08_Code/DiffDock/inference.py", line 81, in <module>
    test_dataset = PDBBind(transform=None, root='', protein_path_list=protein_path_list, ligand_descriptions=ligand_descriptions,
  File "/share/lcbcsrv5/lcbcdata/duerr/PhD/08_Code/DiffDock/datasets/pdbbind.py", line 102, in __init__
    self.inference_preprocessing()
  File "/share/lcbcsrv5/lcbcdata/duerr/PhD/08_Code/DiffDock/datasets/pdbbind.py", line 208, in inference_preprocessing
    mol.RemoveAllConformers()
```

**Comment by HannesStark** [comment]
Thanks for pointing out the typo in the README - it is fixed now!

Regarding the error when using --ligand, is there an error message that you could share?

**Comment by duerrsimon** [comment]
it's below the first error message and seems related to rdkit. 
SMILES string works but not SDF files. 
rdkit is installed. 
```>>> import rdkit
>>> rdkit.__version__
'2022.03.5'```

**Comment by duerrsimon** [comment]
The files I am using are attached to this issue https://github.com/gcorso/DiffDock/issues/1

**Comment by duerrsimon** [comment]
I traced back the error and the issue is that sanitization is on and fails on the provided files but no error/warning is thrown. 
This is the error that should be raised. 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
rdkit.Chem.rdchem.AtomValenceException: Explicit valence for atom # 14 C, 6, is greater than permitted
```
