### ISSUE TITLE
LM embeddings "did not have the right length"

### ISSUE THREAD

**Issue by slochower** [gcorso/DiffDock#33]
Hi, could you shed some light on the error "LM embeddings for complex... did not have the right length for the protein"?

I'm trying to run on a single protein-ligand complex, and I'm providing a prepared protein PDB and ligand SDF. I can see in the code where this is generated https://github.com/gcorso/DiffDock/blob/c32ec5b4332772aeb47652f7c0bdb500b8c17b88/datasets/pdbbind.py#L322 but I'm not sure I understand what is causing the `if` statement to be true. 

Here is the exact error:

```
python -m inference --protein_path data/XXX.pdb --ligand data/YYY.sdf --out_dir results/user_predictions_small --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise
Reading molecules and generating local structures with RDKit
1it [00:00, 23.30it/s]
Reading language model embeddings.
Generating graphs for ligands and proteins
loading complexes:   0%|                                                                                                                                                                                        | 0/1 [00:00<?, ?it/s]LM embeddings for complex data/XXX.pdb____data/YYY.sdf did not have the right length for the protein. Skipping data/XXX.pdb____data/YYY.sdf.
loading complexes: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.47s/it]
loading data from memory:  data/cache_torsion/limit0_INDEX_maxLigSizeNone_H0_recRad15.0_recMax24_esmEmbeddings2279325814/heterographs.pkl
Number of complexes:  0
/cluster/home/slochowe/anaconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/cluster/home/slochowe/anaconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/cluster/home/slochowe/anaconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/_methods.py:265: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/cluster/home/slochowe/anaconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/_methods.py:223: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
/cluster/home/slochowe/anaconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/_methods.py:257: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/cluster/home/slochowe/anaconda3/envs/diffdock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cluster/home/slochowe/anaconda3/envs/diffdock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cluster/home/slochowe/explorations/DiffDock/inference.py", line 81, in <module>
    test_dataset = PDBBind(transform=None, root='', protein_path_list=protein_path_list, ligand_descriptions=ligand_descriptions,
  File "/cluster/home/slochowe/explorations/DiffDock/datasets/pdbbind.py", line 111, in __init__
    print_statistics(self.complex_graphs)
  File "/cluster/home/slochowe/explorations/DiffDock/datasets/pdbbind.py", line 376, in print_statistics
    print(f"{name[i]}: mean {np.mean(array)}, std {np.std(array)}, max {np.max(array)}")
  File "<__array_function__ internals>", line 180, in amax
  File "/cluster/home/slochowe/anaconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2793, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/cluster/home/slochowe/anaconda3/envs/diffdock/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by hgbrian** [comment]
Hi, I believe I know the answer to this.

Try adding `--truncation_seq_length 30000` to this line (or any big number, the default is 1000 aas, approx):

```python extract.py esm2_t33_650M_UR50D data/prepared_for_esm.fasta data/esm2_output --repr_layers 33 --include per_tok --truncation_seq_length 30000```

**Comment by slochower** [comment]
Got it, thanks. Yep, this solved the problem.

**Comment by FelixHan-hub** [comment]
Sincerely, I've encountered same problems and I am quite not knowing how to add --truncation_seq_length 30000 .I have only used inference.py. cryyyyyinggggg!!
