### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'origin'

### ISSUE THREAD

**Issue by francoviscarra** [gcorso/DiffDock#38]
Hi, I tried running the model for a protein-ligand complex with the following commands:

```
python datasets/esm_embedding_preparation.py --protein_path /brahma_hd/a7_allosteric/docking/7ekt/diffdock/7ekt.pdb --out_file data/prepared_for_esm.fasta 

git clone https://github.com/facebookresearch/esm
cd esm
pip install -e .
cd ..
HOME=esm/model_weights python esm/scripts/extract.py esm2_t33_650M_UR50D data/prepared_for_esm.fasta data/esm2_output --repr_layers 33 --include per_tok

python -m inference --out_dir /brahma_hd/a7_allosteric/docking/7ekt/diffdock/ --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise --protein_path /brahma_hd/a7_allosteric/docking/7ekt/diffdock/7ekt.pdb --ligand /brahma_hd/a7_allosteric/docking/7ekt/diffdock/EQ04.mol2
```

But I get this error when running inference:
```

Traceback (most recent call last):
  File "/biggin/b196/scro4068/miniconda3/envs/diffdock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/biggin/b196/scro4068/miniconda3/envs/diffdock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/biggin/b196/scro4068/opt/DiffDock/inference.py", line 16, in <module>
    from datasets.pdbbind import PDBBind
  File "/biggin/b196/scro4068/opt/DiffDock/datasets/pdbbind.py", line 22, in <module>
    from utils.utils import read_strings_from_txt
  File "/biggin/b196/scro4068/opt/DiffDock/utils/utils.py", line 12, in <module>
    from torch_geometric.nn.data_parallel import DataParallel
  File "/biggin/b196/scro4068/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_geometric/nn/__init__.py", line 3, in <module>
    from .sequential import Sequential
  File "/biggin/b196/scro4068/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_geometric/nn/sequential.py", line 8, in <module>
    from torch_geometric.nn.conv.utils.jit import class_from_module_repr
  File "/biggin/b196/scro4068/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_geometric/nn/conv/__init__.py", line 25, in <module>
    from .spline_conv import SplineConv
  File "/biggin/b196/scro4068/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_geometric/nn/conv/spline_conv.py", line 16, in <module>
    from torch_spline_conv import spline_basis, spline_weighting
  File "/biggin/b196/scro4068/miniconda3/envs/diffdock/lib/python3.9/site-packages/torch_spline_conv/__init__.py", line 11, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
AttributeError: 'NoneType' object has no attribute 'origin'

```

Any ideas?

Best regards,
Franco

**Comment by francoviscarra** [comment]
Fixed by reinstalling CUDA toolkit.
