### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/prepared_for_esm.fasta'

### ISSUE THREAD

**Issue by alpha-beta-user** [gcorso/DiffDock#46]
Hi, when I follow this command:
`HOME=esm/model_weights python esm/scripts/extract.py esm2_t33_650M_UR50D data/prepared_for_esm.fasta data/esm2_output --repr_layers 33 --include per_tok
`
it get an error.
`Traceback (most recent call last):
  File "/home/icer/my_prj/diffdock/DiffDock/esm/scripts/extract.py", line 137, in <module>
    main(args)
  File "/home/icer/my_prj/diffdock/DiffDock/esm/scripts/extract.py", line 74, in main
    dataset = FastaBatchedDataset.from_file(args.fasta_file)
  File "/home/icer/my_prj/diffdock/DiffDock/esm/esm/data.py", line 39, in from_file
    with open(fasta_file, "r") as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'data/prepared_for_esm.fasta'`

**Comment by HannesStark** [comment]
You would need to follow the previous commands in the readme which generates the file data/prepared_for_esm.fasta
