### ISSUE TITLE
errors :UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__

### ISSUE THREAD

**Issue by MachineGUN001** [gcorso/DiffDock#78]
I installed pytorch according to the instructions in the readme, but it still reports errors during the run, as follows. 
how can I fix the issues up? thanks,

`C:\\Docking_Lab\DiffDock>python` -m inference --protein_ligand_csv data/protein_ligand_example2_csv.csv --out_dir results/user_predictions_testset --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise
loading data from memory:  data/cache_torsion\limit0_INDEX_maxLigSizeNone_H0_recRad15.0_recMax24_esmEmbeddings3286118574\heterographs.pkl
Number of complexes:  3
radius protein: mean 39.200199127197266, std 0.0, max 39.200199127197266
radius molecule: mean 6.382544040679932, std 1.7080236673355103, max 7.651032447814941
distance protein-mol: mean 44.75419235229492, std 0.2661869525909424, max 45.13044738769531
rmsd matching: mean 0.0, std 0.0, max 0
HAPPENING | confidence model uses different type of graphs than the score model. Loading (or creating if not existing) the data for the confidence model now.
loading data from memory:  data/cache_torsion_allatoms\limit0_INDEX_maxLigSizeNone_H0_recRad15.0_recMax24_atomRad5_atomMax8_esmEmbeddings3286118574\heterographs.pkl
Number of complexes:  3
radius protein: mean 39.200199127197266, std 0.0, max 39.200199127197266
radius molecule: mean 5.83909797668457, std 1.34346604347229, max 7.116300582885742
distance protein-mol: mean 44.50131607055664, std 0.3297865390777588, max 44.74887466430664
rmsd matching: mean 0.0, std 0.0, max 0
C:\Users\LSY\.conda\envs\diffdock\lib\site-packages\torch\jit\_check.py:181: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  **warnings.warn("The TorchScript type system doesn't support "**
Traceback (most recent call last):
  File "C:\..\.conda\envs\diffdock\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\..\.conda\envs\diffdock\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\...\Docking_Lab\DiffDock\inference.py", line 120, in <module>
    confidence_model = get_model(confidence_model_args, device, t_to_sigma=t_to_sigma, no_parallel=True, confidence_mode=True)
  File "C:\..\Docking_Lab\DiffDock\utils\utils.py", line 100, in get_model
    model = model_class(t_to_sigma=t_to_sigma,
TypeError: __init__() got an unexpected keyword argument 'no_aminoacid_identities'`

**Comment by gcorso** [comment]
Hi @MachineGUN001 
Are you running the latest version of the repo? If not could you pull the recent changes and try to rerun?

**Comment by MachineGUN001** [comment]
> Hi @MachineGUN001 Are you running the latest version of the repo? If not could you pull the recent changes and try to rerun?

thanks for your feedback,  I will update the latest vesrion and try that agin.

**Comment by MachineGUN001** [comment]
I pull the recent py scripts with the latest verstion of the repo and run it again.
it looks there are some new errors

(diffdock) C:\Users\SBBD\Cheminfo_Workshop\Docking_Lab\DiffDock>python -m inference --protein_ligand_csv data/protein_ligand_example2_csv.csv --out_dir results/user_predictions_testset --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise
Traceback (most recent call last):
  File "C:\Users\.conda\envs\diffdock\lib\site-packages\pandas\core\indexes\base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'complex_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\.conda\envs\diffdock\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\.conda\envs\diffdock\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\SBBD\Cheminfo_Workshop\Docking_Lab\DiffDock\inference.py", line 55, in <module>
    complex_name_list = set_nones(df['complex_name'].tolist())
  File "C:\Users\.conda\envs\diffdock\lib\site-packages\pandas\core\frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\.conda\envs\diffdock\lib\site-packages\pandas\core\indexes\base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'complex_name'

**Comment by gcorso** [comment]
In the new version the format of the CSV file changed slightly, could you adapt your CSV to conform with the new example provided?

**Comment by MachineGUN001** [comment]
> In the new version the format of the CSV file changed slightly, could you adapt your CSV to conform with the new example provided?
I should use the new format of CSV. attached please see my edits with the path way of protein and ligand.
but the errors still occur and same as previous one.
[testset_csv2.csv](https://github.com/gcorso/DiffDock/files/10767604/testset_csv2.csv)

(diffdock) C:\Users\SBBD\Cheminfo_Workshop\Docking_Lab\DiffDock>python -m inference --protein_ligand_csv data/testset_csv2.csv --out_dir results/user_predictions_testset --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise
Traceback (most recent call last):
  File "C:\Users\.conda\envs\diffdock\lib\site-packages\pandas\core\indexes\base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'complex_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\.conda\envs\diffdock\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\.conda\envs\diffdock\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\SBBD\Cheminfo_Workshop\Docking_Lab\DiffDock\inference.py", line 55, in <module>
    complex_name_list = set_nones(df['complex_name'].tolist())
  File "C:\Users\.conda\envs\diffdock\lib\site-packages\pandas\core\frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\.conda\envs\diffdock\lib\site-packages\pandas\core\indexes\base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'complex_name'

**Comment by MachineGUN001** [comment]
the first two steps work well

(diffdock) C:\Users\SBBD\Cheminfo_Workshop\Docking_Lab\DiffDock>python datasets/esm_embedding_preparation.py --protein_ligand_csv data/protein1_ligand_example_csv.csv --out_file data/prepared_1a0q_for_esm_testset.fasta
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.10it/s]

(diffdock) C:\Users\SBBD\Cheminfo_Workshop\Docking_Lab\DiffDock>python esm/scripts/extract.py esm2_t33_650M_UR50D data/prepared_1a0q_for_esm_testset.fasta data/esm2_output --repr_layers 33 --include per_tok
Read data\prepared_1a0q_for_esm_testset.fasta with 2 sequences
Processing 1 of 1 batches (2 sequences)

**Comment by gcorso** [comment]
The instructions for running the model have slightly changed, now the csv file should be of the form https://github.com/gcorso/DiffDock/blob/main/data/protein_ligand_example_csv.csv and you no longer need to run the first two preprocessing step you showed. Please check the instructions in the README.md file

**Comment by MachineGUN001** [comment]
> The instructions for running the model have slightly changed, now the csv file should be of the form https://github.com/gcorso/DiffDock/blob/main/data/protein_ligand_example_csv.csv and you no longer need to run the first two preprocessing step you showed. Please check the instructions in the README.md file

thanks for your help. that works after using the right format of CSV your mentioned.
pls close the issue. thanks,

**Comment by gcorso** [comment]
Great!
